spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: database
server:
  port: 9090
azure:
  storage:
    connection-string: connection_string_here
    container-name: container_name_here